ALTER TABLE PAGOS_EFECTIVIDAD ADD ESTADO VARCHAR2(50);
COMMIT;
UPDATE PAGOS_EFECTIVIDAD SET ESTADO = 'ABIERTO' WHERE NRO_DOC IN (SELECT DISTINCT NRO_DOCUMENTO FROM TABLA_ASIGNACION_ACTUAL WHERE SEGMENTO IS NULL);
COMMIT;
UPDATE PAGOS_EFECTIVIDAD SET ESTADO = 'CERRADO' WHERE ESTADO IS NULL;
