DROP TABLE ASIGNACION_HISTORICO;
CREATE TABLE ASIGNACION_HISTORICO AS (
 
SELECT A.FECHA, A.SERVICIO_ORIGEN,A.RUC_DNI, A.CUST_ACCOUNT, A.MONEDA,A.NRO_DOCUMENTO, A.FECHA_EMISION, A.FECHA_VENCIMIENTO
, SUM(A.MON_ORIGINAL)MON_ORIGINAL, SUM(A.TOTAL_A_GESTIONAR_S)TOTAL_A_GESTIONAR_S, A.NOMBRE_CARTERA, A.GESTOR, A.LIQUIDACION, A.TIPO_CONTRATO
, UPPER(A.REGION)REGION, A.ESTADOTOTAL, A.TRAMODEUDA, A.ACCION, A.FECHA_FIN, A.CICLO, A.PRODUCTO, A.ETAPA
, A.PERFIL, A.ETAPA2,'CERRADO' ESTADO
FROM TABLA_ASIGNACION_PASADA A
WHERE SEGMENTO IS  NULL
AND NOMBRE_CARTERA IS NOT NULL
GROUP BY A.FECHA, A.SERVICIO_ORIGEN,A.RUC_DNI, A.CUST_ACCOUNT, A.MONEDA,A.NRO_DOCUMENTO, A.FECHA_EMISION, A.FECHA_VENCIMIENTO
,  A.NOMBRE_CARTERA, A.GESTOR, A.LIQUIDACION, A.TIPO_CONTRATO
, UPPER(A.REGION), A.ESTADOTOTAL, A.TRAMODEUDA, A.ACCION, A.FECHA_FIN, A.CICLO, A.PRODUCTO, A.ETAPA
, A.PERFIL, A.ETAPA2,'CERRADO'

UNION

SELECT  A.FECHA, A.SERVICIO_ORIGEN,A.RUC_DNI, A.CUST_ACCOUNT, A.MONEDA,A.NRO_DOCUMENTO, A.FECHA_EMISION, A.FECHA_VENCIMIENTO
, SUM(A.MON_ORIGINAL)MON_ORIGINAL, SUM(A.TOTAL_A_GESTIONAR_S)TOTAL_A_GESTIONAR_S, A.NOMBRE_CARTERA, A.GESTOR, A.LIQUIDACION, A.TIPO_CONTRATO
, UPPER(A.REGION)REGION, A.ESTADOTOTAL, A.TRAMODEUDA, A.ACCION, A.FECHA_FIN, A.CICLO, A.PRODUCTO, A.ETAPA
, A.PERFIL, A.ETAPA2,'ABIERTO' ESTADO
FROM TABLA_ASIGNACION_ACTUAL A
WHERE SEGMENTO IS  NULL
AND NOMBRE_CARTERA IS NOT NULL
GROUP BY A.FECHA, A.SERVICIO_ORIGEN,A.RUC_DNI, A.CUST_ACCOUNT, A.MONEDA,A.NRO_DOCUMENTO, A.FECHA_EMISION, A.FECHA_VENCIMIENTO
,  A.NOMBRE_CARTERA, A.GESTOR, A.LIQUIDACION, A.TIPO_CONTRATO
, UPPER(A.REGION), A.ESTADOTOTAL, A.TRAMODEUDA, A.ACCION, A.FECHA_FIN, A.CICLO, A.PRODUCTO, A.ETAPA
, A.PERFIL, A.ETAPA2,'ABIERTO');




DROP TABLE ASIGNACION_PAGOS;
CREATE TABLE ASIGNACION_PAGOS AS
(
SELECT A.FECHA,A.GESTOR,P.NRO_CUENTA,P.CUST_ACCOUNT_ID,P.CUSTOMER_ID,P.NRO_DOC, 
SUM(P.PAGO_EFECTIVIDAD)PAGO_EFECTIVIDAD,SUM(PAGO_APLICADO_SOLES)PAGO_APLICADO_SOLES,
MAX(TRUNC(FECHA_REGISTRO_APLIC_PAGO) - TRUNC(A.FECHA)) DIA_PAGO ,
MAX(FECHA_REGISTRO_APLIC_PAGO) FECHA_REGISTRO_APLIC_PAGO
FROM (SELECT * FROM PAGOS_EFECTIVIDAD WHERE TRUNC(FECHA_REGISTRO_APLIC_PAGO)<trunc(SYSDATE)) P,
(SELECT FECHA,COALESCE(FECHA_FIN, TRUNC(LAST_DAY(SYSDATE)))FECHA_FIN,GESTOR,CUST_ACCOUNT, NRO_DOCUMENTO FROM ASIGNACION_HISTORICO)A

WHERE 1=1
AND P.NRO_CUENTA=A.CUST_ACCOUNT
AND P.NRO_DOC=A.NRO_DOCUMENTO
AND P.FECHA_REGISTRO_APLIC_PAGO(+)>=A.FECHA
AND P.FECHA_REGISTRO_APLIC_PAGO(+)<=A.FECHA_FIN
GROUP BY A.FECHA,A.GESTOR,P.NRO_CUENTA,P.CUST_ACCOUNT_ID,P.CUSTOMER_ID,P.NRO_DOC
);



