DROP TABLE PAGOS_EFECTIVIDAD PURGE;
CREATE TABLE PAGOS_EFECTIVIDAD
(       
  NRO_CUENTA               VARCHAR2(50),
  CUST_ACCOUNT_ID          VARCHAR2(50),
  CUSTOMER_ID              VARCHAR2(50),
  RUC                      VARCHAR2(50),
  ORIGEN                   VARCHAR2(50),
  CUSTOMER_TRX_ID          VARCHAR2(50),
  NRO_DOC                  VARCHAR2(50),
  EMISION                  DATE,
  VENCIMIENTO              DATE,
  MONEDA                   VARCHAR2(50),
  MONTO_FAC                NUMBER,
  MONTO_FAC_SOLES          NUMBER,
  IDFAC                    VARCHAR2(50),
  NRO_PAGO                 VARCHAR2(50),
  PAGO_APLICADO             NUMBER,
  PAGO_EFECTIVIDAD             NUMBER,
  PAGO_APLICADO_SOLES       NUMBER,
  FECHA_PAGO                 DATE,
  FECHA_HORA_PAGO            DATE,
  FECHA_APLICADA             DATE,
  FECHA_REGISTRO_APLIC_PAGO  DATE

);
CREATE INDEX PAGOS_EFECTIVIDAD_IDX1 ON PAGOS_EFECTIVIDAD (CUST_ACCOUNT_ID);
CREATE INDEX PAGOS_EFECTIVIDAD_IDX2 ON PAGOS_EFECTIVIDAD (NRO_CUENTA);
