SELECT 
B.ACCOUNT_NUMBER NRO_CUENTA,
TO_CHAR(B.CUST_ACCOUNT_ID)CUST_ACCOUNT_ID,
B.ORIG_SYSTEM_REFERENCE CUSTOMER_ID,
HP.JGZZ_FISCAL_CODE RUC,
B.ATTRIBUTE19 ORIGEN,
TO_CHAR(C.CUSTOMER_TRX_ID) CUSTOMOER_TRX_ID,
TO_CHAR(C.TRX_NUMBER) NRO_DOC,
C.TRX_DATE EMISION,
C.DUE_DATE VENCIMIENTO,
C.INVOICE_CURRENCY_CODE MONEDA,
C.AMOUNT_DUE_ORIGINAL MONTO_FAC,
DECODE(C.INVOICE_CURRENCY_CODE,'PEN',NVL(C.AMOUNT_DUE_ORIGINAL,0),'USD',NVL(C.AMOUNT_DUE_ORIGINAL,0) * C.EXCHANGE_RATE) MONTO_FAC_SOLES,
R.INTERFACE_HEADER_ATTRIBUTE1 IDFAC,
D.RECEIPT_NUMBER NRO_PAGO,
T.AMOUNT_APPLIED PAGO_APLICADO,
NVL(DECODE(C.INVOICE_CURRENCY_CODE,'PEN',T.AMOUNT_APPLIED ,'USD',T.AMOUNT_APPLIED  * R.EXCHANGE_RATE),0)PAGO_EFECTIVIDAD,
NVL(DECODE(T.TRANS_TO_RECEIPT_RATE,NULL,T.AMOUNT_APPLIED * D.EXCHANGE_RATE,T.AMOUNT_APPLIED * T.TRANS_TO_RECEIPT_RATE),T.AMOUNT_APPLIED)PAGO_APLICADO_SOLES,
D.RECEIPT_DATE FECHA_PAGO,
TO_DATE(D.ATTRIBUTE4, 'YYYYMMDDHH24MISS')FECHA_HORA_PAGO, 
T.APPLY_DATE FECHA_APLICADA,
T.CREATION_DATE FECHA_REGISTRO_APLIC_PAGO
FROM AR.HZ_CUST_ACCOUNTS               B,
     AR.RA_CUSTOMER_TRX_ALL            R,
     AR.AR_PAYMENT_SCHEDULES_ALL       C,
     AR.AR_CASH_RECEIPTS_ALL           D,
     AR.AR_RECEIVABLE_APPLICATIONS_ALL T,
     AR.HZ_PARTIES                     HP,
     XBOL.TS_OAC_CL_TRACE_PAGOS_ALL F,
     AR.AR_RECEIPT_METHODS         RM,
     AR.RA_CUST_TRX_TYPES_ALL RCTT
WHERE B.CUST_ACCOUNT_ID = R.BILL_TO_CUSTOMER_ID
   AND R.CUSTOMER_TRX_ID = C.CUSTOMER_TRX_ID
   AND D.PAY_FROM_CUSTOMER = B.CUST_ACCOUNT_ID
   AND HP.PARTY_ID = B.PARTY_ID
   AND T.APPLICATION_TYPE = 'CASH' 
   AND T.DISPLAY = 'Y'
   AND T.APPLIED_CUSTOMER_TRX_ID = R.CUSTOMER_TRX_ID
   AND D.CASH_RECEIPT_ID = T.CASH_RECEIPT_ID
   AND R.CUST_TRX_TYPE_ID(+)=RCTT.CUST_TRX_TYPE_ID
   AND D.ATTRIBUTE7 = F.TRACE_ID
   AND D.RECEIPT_NUMBER  = F.P_NRO_OPERACION
   AND D.RECEIPT_METHOD_ID = RM.RECEIPT_METHOD_ID
   AND D.STATUS IN ('APP','UNAPP')
   AND C.TRX_NUMBER IN 
        (
        {Nro_Doc}
        )
